platform :osx, '10.15'

target 'pod_use_frameworks' do
  use_frameworks!
  pod 'CombineTraits', :path => '../../../..'
end

target 'pod_use_modular_headers' do
  use_modular_headers!
  pod 'CombineTraits', :path => '../../../..'
end
